sudo: required

language: ruby

services:
  - docker

before_install:
- ssh-keygen -f new -t rsa -N ''
- ssh-add new
- docker build -t mybase .
- sudo docker run --privileged=true -v /var/run/docker.sock:/var/run/docker.sock -d --name 'mydoc' -t mybase /sbin/my_init
- docker inspect -format '{{ .NetworkSettings.IPAddress }}' 'mydoc'

script:
- bundle exec rake test

