sudo: required

language: ruby

services:
  - docker

before_install:
- eval `ssh-agent`
- ssh-keygen -f new -t rsa -N ''
- ssh-add new
- docker build -t mybase .
- sudo docker run --privileged=true -d --name 'mydoc' -t mybase /sbin/my_init
- sleep 10
- ssh -o StrictHostKeyChecking=n root@$(docker inspect -format '{{ .NetworkSettings.IPAddress }}' 'mydoc') sh -c "curl -L https://get.docker.com/ | sudo sh && service docker start && docker run ubuntu"

script:
- bundle exec rake test

